// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaLtDFj7k1B03dtXFWZhfZTO5EfXgSIWc',
    appId: '1:323142660282:web:61d54cbeb1e501c5f65283',
    messagingSenderId: '323142660282',
    projectId: 'crypto-list-app-7c92e',
    authDomain: 'crypto-list-app-7c92e.firebaseapp.com',
    storageBucket: 'crypto-list-app-7c92e.firebasestorage.app',
    measurementId: 'G-PHY1SZN210',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRRFSgHSZTdtnTDZHD8F4a7yPpF9z-NM',
    appId: '1:323142660282:android:7a396a3f41234478f65283',
    messagingSenderId: '323142660282',
    projectId: 'crypto-list-app-7c92e',
    storageBucket: 'crypto-list-app-7c92e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEttF00YgGdCK90QC2kNtRyAOytaoJAmU',
    appId: '1:323142660282:ios:22f25507f1e131aaf65283',
    messagingSenderId: '323142660282',
    projectId: 'crypto-list-app-7c92e',
    storageBucket: 'crypto-list-app-7c92e.firebasestorage.app',
    iosBundleId: 'com.example.cryptoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEttF00YgGdCK90QC2kNtRyAOytaoJAmU',
    appId: '1:323142660282:ios:22f25507f1e131aaf65283',
    messagingSenderId: '323142660282',
    projectId: 'crypto-list-app-7c92e',
    storageBucket: 'crypto-list-app-7c92e.firebasestorage.app',
    iosBundleId: 'com.example.cryptoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaLtDFj7k1B03dtXFWZhfZTO5EfXgSIWc',
    appId: '1:323142660282:web:e219ef241b5e24cdf65283',
    messagingSenderId: '323142660282',
    projectId: 'crypto-list-app-7c92e',
    authDomain: 'crypto-list-app-7c92e.firebaseapp.com',
    storageBucket: 'crypto-list-app-7c92e.firebasestorage.app',
    measurementId: 'G-3HX45DPQ1C',
  );
}
